# Generated by Django 5.0.6 on 2024-07-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeproducts', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
